name: run_PLSR_example

# Controls when the action will run.
#on:
#  schedule:
#    - cron:  '0 13 * * *'
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  R_LIBS_USER: /usr/local/lib/R/site-library
  LC_ALL: en_US.UTF-8
  NCPUS: 2

jobs:
  run-plsr: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      
    strategy:
      fail-fast: false
      matrix:
        R:
          - "4.0"
 
    steps:
      #check out source code
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      # Run R script
      - name: Run Ely et al. (2019) PLSR Example
        run: |
          source("R/inst/scripts/spectra-trait_ely_leafN_plsr_bootstrap_example.R")
        shell: Rscript {0}