# Run Ely et al 2019 example
name: PLSR_example

# Controls when the action will run.
#on:
#  schedule:
#    - cron:  '0 13 * * *'
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  R_LIBS_USER: /usr/local/lib/R/site-library
  LC_ALL: en_US.UTF-8
  NCPUS: 2

jobs:
  plsr: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
        
    # Load repo and install R
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2

      # Run R script
      - name: Run Ely et al. (2019) PLSR Example
      run: Rscript ./inst/scripts/spectra-trait_ely_leafN_plsr_bootstrap_example.R